let data = {
    "tutorial":[
        {
            "product": "tutorial",
            "review-number" : "1",
            "rate": "1",
            "review-title": "Paid Subscription Required",
            "review-body": "Had I known I’d need to pay a monthly subscription fee I never would have gotten this. I bought in November 2020 and now in May 2021 I’m getting emails that I need to purchase a subscription. Now I can only view the videos live which is fine for the one in my house for checking on my dog but doesn’t work for the one watching my front door incase of break ins or stolen packages. Nest is better, no subscription required.",
            "review-body-translated": "월 구독료를 지불해야 할 줄 알았다면 절대 받지 않았을 것입니다. 2020년 11월에 구매했고 지금 2021년 5월에 구독을 구매해야 한다는 이메일을 받고 있습니다. 이제 나는 비디오를 실시간으로 볼 수만 있습니다. 집에 있는 개를 확인하는 데는 문제가 없지만 침입하거나 소포를 도난당한 경우 현관문을 보는 사람에게는 작동하지 않습니다. Nest가 더 좋으며 구독이 필요하지 않습니다.",
            "helpfulness-rating": null,
        },        
        {
            "product": "tutorial",
            "review-number" : "2",
            "rate": "5",
            "review-title": "Awesome Video Camera; But Set-Up?",
            "review-body": "The Blink Mini video camera is awesome for what it does, once you set it up. The common issue is that it takes slightly more effort to establish an account with Blink and activate the camera. However, once set-up, the camera can be used with either available light or with night vision.Either way, the Blink Mini can detect motion within the scope of the camera's range. The Blink Mini is useful for monitoring home interiors, or areas which might require protection against unauthorized access.The Blink Mini can capture about 10 seconds of video, enough to identify intruders. The Blink Mini will also send push notifications to your mobile device to alert you to unauthorized access.Not only will this save your cherished goods, money, and insurance replacement costs, it will help law enforcement do its job against thieve",
            "review-body-translated": "Blink Mini 비디오 카메라는 설정만 하면 그 기능을 완벽하게 수행합니다. 일반적인 문제는 Blink로 계정을 만들고 카메라를 활성화하는 데 약간 더 많은 노력이 필요하다는 것입니다. 그러나 일단 설정되면 카메라는 사용 가능한 조명 또는 야간 투시경과 함께 사용할 수 있습니다. 어느 쪽이든 Blink Mini는 카메라 범위 내에서 움직임을 감지할 수 있습니다. Blink Mini는 가정 내부 또는 무단 액세스로부터 보호해야 할 수 있는 영역을 모니터링하는 데 유용합니다. Blink Mini는 침입자를 식별하기에 충분한 약 10초 분량의 비디오를 캡처할 수 있습니다. Blink Mini는 또한 무단 액세스를 경고하기 위해 모바일 장치에 푸시 알림을 보냅니다. 이렇게 하면 소중한 물건, 돈 및 보험 교체 비용을 절약할 수 있을 뿐만 아니라 법 집행 기관이 도둑에 대처하는 데 도움이 됩니다.",
            "helpfulness-rating": null,
        }
    ],
    "review":[
        {
            "product": "hand cream",
            "review-number" : "1",
            "rate": "5",
            "review-title": "Good non- greasy cream !",
            "review-body": "I have very dry skin on my hands that tend to peel near the nail beds. I started to use this cream 3-4 times a day for the first few days and now I have resorted to using it once before bed and once in the morning. The regular use of this cream has made my hands smooth and supple, with no dryness or peeling. I recommend this to anybody suffering with dry skin on their hands",
            "review-body-translated": "나는 손톱 침대 근처에서 벗겨지는 경향이 있는 매우 건조한 손 피부를 가지고 있습니다. 나는 처음 며칠 동안 이 크림을 하루에 3-4번 사용하기 시작했고 이제는 자기 전에 한 번, 아침에 한 번 사용하게 되었습니다. 이 크림을 정기적으로 사용하면 건조함이나 벗겨짐 없이 손이 부드럽고 유연해졌습니다. 건조한 손 피부로 고민이신 분들께 추천드려요",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "2",
            "rate": "4",
            "review-title": "Great Hand Moisturizer",
            "review-body": "This lotion leaves my hands feeling so soft and moisturized. Love it. However its best if hands are clean or if you apply it after washing your hands, or else it can leave a sticky feeling.",
            "review-body-translated": "이 로션은 내 손을 너무 부드럽고 촉촉하게 만듭니다. 좋습니다. 하지만 손이 깨끗하거나 손을 씻은 후 바르는 것이 가장 좋습니다. 그렇지 않으면 끈적임이 남을 수 있습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "3",
            "rate": "3",
            "review-title": "So much air",
            "review-body": "I love this product and the quality is amazing but the amount of air that is in the tube is just SAD. I can just tell how less is In there. Its quite disappointing",
            "review-body-translated": "나는 이 제품을 사랑하고 품질은 놀랍지만 튜브에 있는 공기의 양은 그저 슬펐습니다. 나는 제품에 얼마나 적게 담겨있었는지 말할 수 있습니다. 상당히 실망스러웠습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "4",
            "rate": "5",
            "review-title": "Works very well",
            "review-body": "In the winter my hands are usually very dry, and sometimes it can be painful and red. I used some other hand moisturizer, but most of the products I have tried are oily and viscous. It doesn't feel comfortable with that type of moisture on hand. The Aveeno moisturizer feels towards the fresh and wet side. It heals my dry skin within a day.",
            "review-body-translated": "겨울에는 보통 손이 매우 건조하며 때로는 아프고 붉어질 수 있습니다. 다른 핸드 모이스처라이저를 사용해 보았지만, 제가 사용해 본 제품은 대부분 유분기가 많고 점성이 있었습니다. 그런 종류의 제품이 손에 닿는 느낌이 편안하지 않습니다. Aveeno 모이스처라이저는 신선하고 젖은 느낍이 듭니다. 건조한 내 피부를 하루 만에 치유해줍니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "5",
            "rate": "2",
            "review-title": "Half way full and not sealed bottle",
            "review-body": "I like this product, but i got it not sealed and half way full. From reading the other reviews, I'm not the only one. This is really NOT ok that Amazon is shipping these products to customers. I pay for full bottle not half.",
            "review-body-translated": "이 제품은 마음에 드는데 봉인이 되어 있지 않고 반만 찼습니다. 다른 리뷰를 보니 저만 그런게 아닙니다. 아마존이 이러한 제품을 고객에게 배송하는 것은 정말 옳지 않습니다. 나는 절반이 아닌 가득 찬 병을 지불합니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "6",
            "rate": "1",
            "review-title": "The container was 2/3rd empty",
            "review-body": "There is something wrong with the product. It seems to be filled with air and deflates as soon as we remove the cap and start using it. Not even sure if it has 35oz of moisturizer in it. Others have complained about the same.",
            "review-body-translated": "제품에 이상이 있습니다. 캡을 제거하고 사용하기 시작하자마자 공기가 가득 차서 수축되는 것 같습니다. 35oz의 모이스처라이저가 들어 있는지 확실하지 않습니다. 다른 사람들도 같은 불만을 토로했습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "7",
            "rate": "1",
            "review-title": "Do not buy",
            "review-body": "I received the bottle and it was unsealed and barely full. I’ve used this lotion in the past and what I got is not aveeno hand cream. It feels very watered down. I do not recommend buying.",
            "review-body-translated": "병을 받았고 밀봉되지 않았고 거의 가득 찼습니다. 나는 과거에이 로션을 사용했고 내가 얻은 것은 aveeno 핸드 크림이 아닙니다. 물이 많이 빠진 느낌입니다. 구매를 권장하지 않습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "8",
            "rate": "4",
            "review-title": "Not bad but nothing special either",
            "review-body": "This lotion is moisturizing but I've seen it advertised as long-lasting, where it's supposed to last through several hand washes. Unfortunately, this is not so. You definitely need to re-apply the lotion afterwards. The price is reasonable but ultimately I'm taking a star off because it doesn't last and also for the smell, which honestly reminds me of gasoline.",
            "review-body-translated": "이 로션은 보습 효과가 있지만 몇 번 손을 씻어도 지속력이 오래 지속된다고 광고하는 것을 본 적이 있습니다. 불행히도 이것은 그렇지 않습니다. 나중에 로션을 다시 바르셔야 합니다. 가격은 합리적이지만 솔직히 휘발유가 생각나는 냄새와 지속되지 않기 때문에 궁극적으로 별을 뺍니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "9",
            "rate": "2",
            "review-title": "sticky",
            "review-body": "The first picture in the ad is not the one you get. If you scroll down you see one with blue labels which is what I got. This cream is not great. Maybe my hands aren't dry enough(I've been washing 1038292 times a day due to working in the hospital during this Covid crisis) but this lotion does not absorb well and feels sort of 'sticky' even after I wait a while for it to absorb. I'm glad it wasn't completely full in the bottle cuz I want to try something else. It also has that unscented 'scent' that was kind of strong.",
            "review-body-translated": "광고의 첫 번째 사진은 당신이 얻는 것이 아닙니다. 아래로 스크롤하면 내가 얻은 파란색 레이블이 있는 것을 볼 수 있습니다. 이 크림은 별로에요. 손이 많이 건조하지 않은 건 아닐까(이 코로나 사태에 병원 일을 하느라 하루에 1038292번을 씻었다) 그러나 이 로션은 잘 흡수되지 않고 흡수될 때까지 잠시 기다린 후에도 일종의 '끈적임'을 느낍니다. 다른 것을 시도하고 싶기 때문에 병에 완전히 채워지지 않은 것이 기쁩니다. 그것은 또한 일종의 강한 무향 '향기'를 가지고 있습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "10",
            "rate": "5",
            "review-title": "Cured my dry skin",
            "review-body": "Not sure why recently but my hands got really dry and flakey, it hurt. I got this lotion and within two days of consistent use, my hands are back to normal and feeling great.",
            "review-body-translated": "최근에 왜 그런지 모르겠지만 손이 정말 건조하고 벗겨져 아팠습니다. 나는 이 로션을 받았고 지속적으로 사용한 지 이틀 만에 손이 정상으로 돌아왔고 기분이 좋아졌습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "11",
            "rate": "2",
            "review-title": "There was no safety seal on the product!",
            "review-body": "There was no safety seal on the product, and when I went to use it (a little nervous) the bottle seems half empty!! I would really have expected there to be more product in it, and it makes me very concerned as well that there was no safety seal, so like, did someone use it then send it?",
            "review-body-translated": "제품에 안전씰도 없고 사용하러 가보니(조금 불안) 병이 반쯤 비어있는 것 같아요!! 정말 더 많은 제품이 들어있을 거라고 예상했는데, 안전씰이 없는게 너무 걱정스럽기도 하고 그래서 누가 사용하고 보낸 걸까요?",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "12",
            "rate": "1",
            "review-title": "Do not buy this",
            "review-body": "This tube came all dirty, they do not come with a seal, and it's like half the tube is air or has already been used. I bought this to go in a gift basket for someone and I would be embarrassed to give this to them in this condition.",
            "review-body-translated": "이 튜브는 더러워졌고 씰이 함께 제공되지 않으며 튜브의 절반이 공기이거나 이미 사용한 것과 같습니다. 누군가를 위한 선물 바구니에 넣으려고 샀는데 이런 상태에서 선물하기 부끄럽습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "13",
            "rate": "5",
            "review-title": "Great product- weird smell",
            "review-body": "I have eczema on my hands pretty terribly, also I’m allergic to most soaps. This product really helped but I just couldn’t get over the smell :( I can’t even describe it because it’s such an odd smell.",
            "review-body-translated": "나는 손에 습진이 아주 심하게 가지고있습니다. 또한 대부분의 비누에 알레르기가 있습니다. 이 제품은 정말 도움이 되었지만 냄새를 지울 수 없었습니다 :( 너무 기이한 냄새라 뭐라 표현할 수가 없네요..",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "14",
            "rate": "1",
            "review-title": "Clumps up",
            "review-body": "I don’t know what is wrong with this hand cream. but every time I would use it, I would be rubbing it in and it was start to like pill up into little balls and wouldn’t stay on my hands. Didn’t adsorb into hands. Don’t even bother.",
            "review-body-translated": "이 핸드크림은 뭐가 문제인지 모르겠네요. 그러나 사용하려고 할 때 마다 문지르면 알약같은 작은 공처럼 되기 시작했습으며 손에 머물지 않았습니다. 손에 흡수되지 않았습니다. 시간이 아깝습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "15",
            "rate": "4",
            "review-title": "good for dry skin",
            "review-body": "It is more moisturize than other hand cream. My hand is really dry expecially in winter, with this product, my hand can keep moisturing for longer time, but I still need it many times a day. If this product has some scent that would be better for me.",
            "review-body-translated": "다른 핸드크림에 비해 보습력이 좋아요. 특히 겨울에 손이 정말 건조한데 이 제품을 사용하면 손에 수분을 오래 유지할 수 있지만 하루에도 몇 번씩은 필요해요. 이 제품에 향이 있다면 나에게 더 좋을 것 같습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "16",
            "rate": "3",
            "review-title": "Bad shape to tube",
            "review-body": "It was what it said it was, but difficult to get out of tube once it reached halfway or so point. I felt like the usable quantity was rather low.",
            "review-body-translated": "그것은 그것이 말했던 대로이지만, 한 번 중간 정도 지점에 도달하면(사용하면) 튜브에서 빠져 나오기가 어렵습니다. 사용할 수 있는 양이 다소 적다는 느낌이 들었습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "17",
            "rate": "5",
            "review-title": "Works miracles",
            "review-body": "My fingers were so cracked. It was horrifying. Nothing was working and I was at the point we're I was going to go see a doctor. I was recommended this lotion. It took about 3 weeks of applying 3x a day and it completely disappeared. I use it now for my feet and face. It's feels amazing and the scent is so good.",
            "review-body-translated": "내 손가락들은 너무 갈라졌었습니다. 그것은 끔찍했었습니다. 어떤ㅓ도 효과가 없었고 의사에게 진찰을 받으러 가야 하는 시점에 있었습니다. 이 로션을 추천받았습니다. 하루 3번 바르는데 3주정도 걸리더니 완전히 사라졌습니다. 나는 지금 내 발과 얼굴에 그것을 사용합니다. 기분도 좋고 향도 너무 좋아요.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "18",
            "rate": "3",
            "review-title": "Seller did awesome. Product OK.",
            "review-body": "I wash my hands thouroughly and a LOT. I love Aveeno products but this just wasnt enough. It's a good product but for dry hands that get a lot of washing, this just didn't cut it.",
            "review-body-translated": "나는 손을 철저히 씻습니다. 나는 Aveeno 제품을 좋아하지만 이것만은 충분히 좋지 않습니다. 좋은 제품이지만 손을 많이 씻는 건성 손에게는 잘 안 잡히더라고요.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "19",
            "rate": "2/5",
            "review-title": "Package And Description Changed, Product The Same",
            "review-body": "I failed to double check the ingredients so the fault of the purchase was mine but still... This product is a disappointment. The product is NOT a cream. You could pump it from a lotion bottle easily. It isn't greasy and it is an unscented product that really has no scent at all so at least 2 stars in its favor. For now I'm still using Cetaphil cream.I really miss Aveeno's older product lines ;<(",
            "review-body-translated": "원재료를 재차 확인하지 못해 구매의 잘못이 제 잘못이지만 그래도... 이 제품은 실망입니다. 제품은 크림이 아닙니다. 로션 병에서 쉽게 펌핑할 수 있습니다. 끈적임도 없고 정말 향이 전혀 없는 무향 제품이라 별점 2개 이상입니다. 아직까지는 세타필 크림을 쓰고 있습니다. 아비노의 예전 제품 라인이 정말 그립습니다. ;<(",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "20",
            "rate": "4",
            "review-title": "Not bad but nothing special either",
            "review-body": "This lotion is moisturizing but I've seen it advertised as long-lasting, where it's supposed to last through several hand washes. Unfortunately, this is not so. You definitely need to re-apply the lotion afterwards. The price is reasonable but ultimately I'm taking a star off because it doesn't last and also for the smell, which honestly reminds me of gasoline.",
            "review-body-translated": "이 로션은 보습 효과가 있지만 몇 번 손을 씻어도 지속력이 오래 지속된다고 광고하는 것을 본 적이 있습니다. 불행히도 이것은 그렇지 않습니다. 나중에 로션을 다시 바르셔야 합니다. 가격은 합리적이지만 솔직히 휘발유가 생각나는 냄새와 지속되지 않기 때문에 궁극적으로 별을 뺍니다.",
            "helpfulness-rating": null,
        },


        {
            "product": "headphone",
            "review-number" : "1",
            "rate": "2",
            "review-title": "Decent for music, Not for phone calls   음악에 적합, 전화 통화에는 적합하지 않음",
            "review-body": "I like the sound when you played music, but when you received a phone call it sounded like you were in a tunnel and the person on the other end was not happy",
            "review-body-translated": "음악을 틀었을 때의 소리는 마음에 드는데 전화를 받았을 때 마치 터널 속에 있는 것 같았고 상대방은 기분이 좋지 않았다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "2",
            "rate": "4",
            "review-title": "For the price point, these are great little earbuds",
            "review-body": "If you compare these to $80 earbuds, then it's not a fair comparison, right? But for the price, these earbuds charge well, sync up to my phone quickly and feel good in my ears. The sound is fine - it isn't concert quality, but as I said, for the price point, these deliver good sound. The only odd thing is the case. Most earbuds have a full case that protects them when not in use. Not sure why the manufacturer thought this was a spiffy idea - it isn't.",
            "review-body-translated": "80달러짜리 이어폰과 비교하면 공정한 비교가 아니겠죠? 그러나 가격에 비해 이 이어버드는 잘 충전되고 휴대폰과 빠르게 동기화되며 귀에 착 감기는 느낌이 듭니다. 사운드는 괜찮습니다. 콘서트 품질은 아니지만 제가 말했듯이 가격대비 좋은 사운드를 제공합니다. 유일한 이상한 점은 케이스입니다. 대부분의 이어버드에는 사용하지 않을 때 보호하는 전체 케이스가 있습니다. 제조업체가 이것이 기발한 아이디어라고 생각한 이유는 잘 모르겠습니다 - 실제로는 그렇지 않습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "3",
            "rate": "5",
            "review-title": "Well worth it",
            "review-body": "The sound quality is great. I use them for walking, and even outside it helps block a lot of other noises. The call quality is great, as well. I tested them by calling him while out. He said I was very clear. They are very comfortable, and come with three different ear piece size coverings.",
            "review-body-translated": "음질은 훌륭합니다. 나는 걸을 때 사용하고 밖에서도 다른 많은 소음을 차단하는 데 도움이 됩니다. 통화 품질도 훌륭합니다. 외출 중에 전화를 걸어 테스트했습니다. 그는 내 소리가 매우 분명하다고 말했다. 매우 편안하며 세 가지 크기의 이어피스 덮개가 제공됩니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "4",
            "rate": "5",
            "review-title": "Great value for the price",
            "review-body": "As this product is famous for the value for the price, sound quality is good. The battery life is 4 hours and it is not that short compared to other products. But it would be better if this product has a longer battery life. When I consider the price of this TWS earbuds, battery life is acceptable and sound is great.",
            "review-body-translated": "이 제품은 가격대비 가성비로 유명한 만큼 음질도 좋습니다. 배터리 수명은 4시간으로 다른 제품에 비해 그렇게 짧은 편은 아니다. 하지만 이 제품의 배터리 수명이 더 길면 더 좋을 것입니다. 이 TWS 이어버드의 가격을 생각하면 배터리 수명이 적당하고 사운드가 훌륭합니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "5",
            "rate": "1",
            "review-title": "Totally failed after the return window.",
            "review-body": "I liked them a lot but right after my return window closed, the earbuds began messing up. Max volume is now really low on both earbuds. They take forever to connect via bluetooth and they no longer pair together…",
            "review-body-translated": "나는 그것들을 많이 좋아했지만 반환 창이 닫힌 직후 이어 버드가 엉망이되기 시작했습니다. 이제 양쪽 이어버드의 최대 볼륨이 정말 낮습니다. 블루투스를 통해 연결하는 데 시간이 오래 걸리고 더 이상 페어링되지 않습니다...",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "6",
            "rate": "1",
            "review-title": "Not worth it!",
            "review-body": "I wrote a review days ago that was pretty much positive, but now it's been a few days. The one ear bud completely stopped working. Also my wireless earbuds are no longer pairing with my device, so I'm returning them & ordering a whole different brand of earbuds. I learnt my lesson, don't be quick to write a review without first having the product for at least a week or longer.",
            "review-body-translated": "나는 꽤 긍정적인 리뷰를 며칠 전에 썼지만 지금은 며칠이 지났습니다. 한쪽 이어버드가 완전히 작동을 멈췄습니다. 또한 내 무선 이어버드가 더 이상 내 장치와 페어링되지 않으므로 반품하고 완전히 다른 브랜드의 이어버드를 주문합니다. 교훈을 배웠습니다. 최소한 일주일 이상 먼저 제품을 사용하지 않고 리뷰를 작성하지 마십시오.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "7",
            "rate": "3",
            "review-title": "Sound is Great Until I Go for a Walk",
            "review-body": "I was very excited to buy these because I've never had a pair of wireless earbuds before. They're great for the price and nice for listening to music while studying. However, when I went to take my dog for a walk, the sound started cutting in and out really badly. I had walked around the house with my phone in my pocket while wearing the earbuds and they didn't cut out at all. I've used the troubleshooting tips in the instructions but they still cut out badly, especially the longer I'm out. It sucks because I bought these so they wouldn't get tangled in stuff. A tad bummed about that but I still like them for other stuff.",
            "review-body-translated": "나는 전에 한 쌍의 무선 이어폰을 가져본 적이 없었기 때문에 이것을 구입하게 되어 매우 기뻤습니다. 가격대비 훌륭하고 공부하면서 음악을 듣기에 좋습니다. 그런데 강아지를 산책시키러 갔을 때 소리가 정말 심하게 끊기기 시작했습니다. 나는 이어폰을 끼고 주머니에 휴대폰을 넣고 집 주변을 돌아다녔는데 전혀 끊기지 않았다. 지침에 있는 문제 해결 팁을 사용했지만 여전히 끊깁니다. 물건이 엉키지 않게 하려고 구입한건데 별로입니다. 조금 아쉽긴 했지만 그래도 다른 면에서는 좋습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "8",
            "rate": "2",
            "review-title": "Right Earbud stopped working after 1-2 momths",
            "review-body": "It was working perfectly but then one day the right ear stopped working and it was really hard to connect to my computer but this never happened the times before",
            "review-body-translated": "완벽하게 작동하다가 어느 날 오른쪽이 작동을 멈춰서 컴퓨터에 연결하기가 정말 어려웠느데 이전에는 이런 일이 없었습니다",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "9",
            "rate": "5",
            "review-title": "Pretty decent quality at a really decent price",
            "review-body": "If you’re an audio snob or it’s important to you for everyone to know you paid half a car payment for earbuds, this is not the product for you. If, on the other hand, you’re an average music/podcast listener on a budget, these things are kind of hard to beat. They’re comfortable, really easy to pair and the sound quality is fine. Not mind-blowing, but perfectly adequate to my admittedly unrefined ears.",
            "review-body-translated": "당신이 오디오 속물이거나 모든 사람이 당신이 이어폰에 대해 자동차 요금의 절반을 지불했다는 것을 아는 것이 중요하다면 이것은 당신을 위한 제품이 아닙니다. 반면에 예산에 맞는 평균적인 음악/팟캐스트 청취자라면 이러한 것들을 극복하기가 어렵습니다. 그들은 편안하고 페어링하기가 쉽고 음질도 좋습니다. 마음에 들지는 않지만 세련되지 않은 내 귀에는 완벽하게 적합합니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "10",
            "rate": "1",
            "review-title": "2 sets, right side will not work",
            "review-body": "I didn’t expect much for the price but I’ve received 2 sets and I can’t get the right side to work, instructions included don’t help at all. Stay away from this product",
            "review-body-translated": "가격대비 별 기대 안했습니다. 그러나 2세트 받았는데 제대로 작동이 안되고 포함되어있는 설명서가 전혀 도움이 안되네요. 이 제품을 멀리하십시오.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "11",
            "rate": "3",
            "review-title": "earbuds",
            "review-body": "right earbud does not work well and the company was not helpful. I ordered new ones from elsewhere. Stuff happens but the company made no effort to assist me",
            "review-body-translated": "오른쪽 이어폰이 잘 안돌아가고 회사는 도움이 안됨. 다른곳에서 새로 주문했습니다. 상황이 발생했지만 회사에서 나를 도우려고 노력하지 않았습니다",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "12",
            "rate": "2",
            "review-title": "Broke Twice :/",
            "review-body": "I had mine for about three weeks before the right one stopped working completely. I returned and got a replacement and to my surprise the replacement didn't work either! It kept connecting and disconnecting. I was really disappointed. The sound quality was okay and the battery life was meh when it actually worked. Do yourself a favor, save your money and purchase some air pods or another brand of wireless earbuds.",
            "review-body-translated": "나는 오른쪽 것이 완전히 작동을 멈추기 전에 약 3 주 동안 내 것을 가지고있었습니다. 나는 돌아와서 교체품을 받았고 놀랍게도 교체품도 작동하지 않았습니다! 연결과 연결 끊김이 계속되었습니다. 나는 정말로 실망했다. 음질은 괜찮았고 실제로 작동했을 때 배터리 수명은 엉망이었습니다. 자신에게 호의를 베풀고 돈을 절약하고 에어팟이나 다른 브랜드의 무선 이어버드를 구입하십시오.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "13",
            "rate": "5",
            "review-title": "Great for the price and just plain great!",
            "review-body": "Kind of unbelievable for the price. Good sound quality, really impressive battery life and beyond convenient. Pairs with no hassle. The no cover design is actually kind of brilliant.",
            "review-body-translated": "가격에 비해 믿을 수 없는 종류. 좋은 음질, 정말 인상적인 배터리 수명 및 그 이상의 편리함. 번거로움 없이 페어링됩니다. 표지가 없는 디자인은 실제로 훌륭합니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "14",
            "rate": "4",
            "review-title": "Good sound and comfort",
            "review-body": "I was hesitant on buying such a cheap pair of wireless headphones, but seeing how I am without the income to purchase a well known name brand I decided to give these a go with the reviews they had recieved. They are amazing for the price. Now as far as sound I will say that they are a little on the quite side, but seeing how I am going deaf due to years of abuse they do have a great sound. They fit comfortably as well, take a little getting used to but all in all will stay in after a violent head shaking and thrashing.10/10 would recommend if you do not have the means.",
            "review-body-translated": "그렇게 저렴한 무선 헤드폰을 사는 것이 망설여지긴 했지만 수입이 없어서 유명 브랜드를 살 수 없는 것을 보고 그들이 받은 리뷰를 보고 구매하기로 결정했습니다. 가격 대비 훌륭합니다. 이제 소리를 내는 것을 보면 나는 그것들이 조용하다고 말하겠지만, 수년간의 학대로 인해 내가 어떻게 귀머거리가 되는가를 고려하면 그들은 훌륭한 소리를 가지고 있습니다. 편안하게  잘 맞기도 하고, 적응이 좀 걸리긴 하지만, 격렬한 머리를 흔들고 쓰다듬어 준 뒤에도 대체로 유지될 것입니다. 여유가 없다면 10/10을 추천합니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "15",
            "rate": "4",
            "review-title": "Good",
            "review-body": "Great bang for buck, decent bass, they tend to jiggle out of your ear if you go on long distance runs. But this is not big deal. They sound really good for the price. So far these are the best BT pods that are >$30",
            "review-body-translated": "아주 훌륭합니다, 베이스가 괜찮습니다, 장거리 달리기를 하면 귀에서 튕겨져 나오는 경향이 있어. 하지만 이건 큰 문제가 아닙니다. 가격 대비 아주 좋은 것 같아요. 30달러가 넘지 않는 것 중에 최고의 BT pod입니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "16",
            "rate": "4",
            "review-title": "Surprisingly great!",
            "review-body": "I bought these to test myself on how I could handle wireless earbuds before I spent a lot of money on google buds or air pods, but these were great for the price. They lasted a solid 9 months of almost daily use for up to 12 hours a day, through sweat and heat. The sound quality was decent, and the battery life of the holder/charger could last me days in between charges. I ultimately bought some google pods, but these served me well for almost a year before one of them quit working, but for the price that was way longer than I expected.",
            "review-body-translated": "구글 버드나 에어팟에 많은 돈을 쓰기 전에 무선 이어버드를 어떻게 다룰 수 있는지 테스트하기 위해 구입했지만 가격대비 훌륭했습니다. 그것들은 땀과 열을 속에서 거의 매일 최대 12시간 동안 9개월 동안 계속 사용되었습니다. 음질은 괜찮았고 홀더/충전기의 배터리 수명은 충전 사이에 며칠을 지속할 수 있었습니다. 궁극적으로 일부 Google 포드를 구입했지만 그 중 하나가 작동을 중단하기 전까지 거의 1년 동안 잘 사용했습니다. 하지만 가격이 예상보다 훨씬 비쌌습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "17",
            "rate": "5",
            "review-title": "Works great for walking and running! Awesome price!",
            "review-body": "I bought these for a 5k training and they work great! I only use one so that I can still hear things around me. They are clear with good quality. I sweat a ton and they stay in. I do readjust them at times but I haven't yet found any that I didn't have to do that. And for the price, I definitely won't complain. These are just what I needed for much less cost!",
            "review-body-translated": "5km 훈련용으로 구입했는데 잘 작동합니다! 나는 여전히 주변의 소리를들을 수 있도록 하나만 사용합니다. 그들은 좋은 품질이며 소리가 명확합니다. 나는 엄청난 땀을 흘렸었고 그들은 귀에 머물러 있었습니다. 나는 때때로 그것을 재조정하지만 나는 아직 내가 조정 할 필요가없을 때을 찾지 못했습니다. 그리고 가격면에서 나는 확실히 불평하지 않을 것입니다. 이것들은 내가 필요로 한 것인데 훨씬 더 저렴한 가격입니다!",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "18",
            "rate": "3",
            "review-title": "Trouble connecting",
            "review-body": "The headphones themselves are fine but they struggle to connect to my phone I often have to turn Bluetooth on and off a few times before I can use them",
            "review-body-translated": "헤드폰 자체는 괜찮은데 핸드폰 연결이 잘 안 됩니다. 블루투스를 몇 번 껐다 켜야 사용할 수 있습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "19",
            "rate": "1",
            "review-title": "Your Earbuds will no longer work after a year - Do not buy this.",
            "review-body": "Your Earbuds will no longer work after a year - Do not buy this. The battery in the base won't take a change after a year. So the earbuds are essentially dead.",
            "review-body-translated": "당신의 이어폰은 1년 후에 더 이상 작동하지 않을 것입니다 - 이것을 사지 마십시오. 베이스의 배터리는 1년이 지나도 교체가 안 됩니다. 그럼 이어폰은 근본적으로 죽습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "headphone",
            "review-number" : "20",
            "rate": "2",
            "review-title": "Uncomfortable",
            "review-body": "These aren’t the most expensive earbuds out there so I didn’t expect much, but the sound is ok. They are bulky and uncomfortable, once you put them in the case to charge it’s difficult pulling them back out. Need a better design solution.",
            "review-body-translated": "이게 제일 비싼 이어폰이 아니라서 별 기대는 안 했는데, 소리가 괜습니다. 부피가 크고 불편해서 한 번 충전하려고 케이스에 넣으면 다시 꺼내기가 어렵습니다. 더 나은 디자인 솔루션이 필요합니다.",
            "helpfulness-rating": null,
        },
    ]
}