let data = {
    "review":[
        {
            "product": "hand cream",
            "review-number" : "1",
            "rate": "5",
            "review-title": "Good non- greasy cream !",
            "review-body": "I have very dry skin on my hands that tend to peel near the nail beds. I started to use this cream 3-4 times a day for the first few days and now I have resorted to using it once before bed and once in the morning. The regular use of this cream has made my hands smooth and supple, with no dryness or peeling. I recommend this to anybody suffering with dry skin on their hands",
            "review-body-translated": "나는 손톱 침대 근처에서 벗겨지는 경향이 있는 매우 건조한 손 피부를 가지고 있습니다. 나는 처음 며칠 동안 이 크림을 하루에 3-4번 사용하기 시작했고 이제는 자기 전에 한 번, 아침에 한 번 사용하게 되었습니다. 이 크림을 정기적으로 사용하면 건조함이나 벗겨짐 없이 손이 부드럽고 유연해졌습니다. 건조한 손 피부로 고민이신 분들께 추천드려요",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "2",
            "rate": "4",
            "review-title": "Great Hand Moisturizer",
            "review-body": "This lotion leaves my hands feeling so soft and moisturized. Love it. However its best if hands are clean or if you apply it after washing your hands, or else it can leave a sticky feeling.",
            "review-body-translated": "이 로션은 내 손을 너무 부드럽고 촉촉하게 만듭니다. 좋습니다. 하지만 손이 깨끗하거나 손을 씻은 후 바르는 것이 가장 좋습니다. 그렇지 않으면 끈적임이 남을 수 있습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "4",
            "rate": "3",
            "review-title": "So much air",
            "review-body": "I love this product and the quality is amazing but the amount of air that is in the tube is just SAD. I can just tell how less is In there. Its quite disappointing",
            "review-body-translated": "나는 이 제품을 사랑하고 품질은 놀랍지만 튜브에 있는 공기의 양은 그저 슬펐습니다. 나는 제품에 얼마나 적게 담겨있었는지 말할 수 있습니다. 상당히 실망스러웠습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "4",
            "rate": "5",
            "review-title": "Works very well",
            "review-body": "In the winter my hands are usually very dry, and sometimes it can be painful and red. I used some other hand moisturizer, but most of the products I have tried are oily and viscous. It doesn't feel comfortable with that type of moisture on hand. The Aveeno moisturizer feels towards the fresh and wet side. It heals my dry skin within a day.",
            "review-body-translated": "겨울에는 보통 손이 매우 건조하며 때로는 아프고 붉어질 수 있습니다. 다른 핸드 모이스처라이저를 사용해 보았지만, 제가 사용해 본 제품은 대부분 유분기가 많고 점성이 있었습니다. 그런 종류의 제품이 손에 닿는 느낌이 편안하지 않습니다. Aveeno 모이스처라이저는 신선하고 젖은 느낍이 듭니다. 건조한 내 피부를 하루 만에 치유해줍니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "5",
            "rate": "2",
            "review-title": "Half way full and not sealed bottle",
            "review-body": "I like this product, but i got it not sealed and half way full. From reading the other reviews, I'm not the only one. This is really NOT ok that Amazon is shipping these products to customers. I pay for full bottle not half.",
            "review-body-translated": "이 제품은 마음에 드는데 봉인이 되어 있지 않고 반만 찼습니다. 다른 리뷰를 보니 저만 그런게 아닙니다. 아마존이 이러한 제품을 고객에게 배송하는 것은 정말 옳지 않습니다. 나는 절반이 아닌 가득 찬 병을 지불합니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "6",
            "rate": "1",
            "review-title": "The container was 2/3rd empty",
            "review-body": "There is something wrong with the product. It seems to be filled with air and deflates as soon as we remove the cap and start using it. Not even sure if it has 35oz of moisturizer in it. Others have complained about the same.",
            "review-body-translated": "제품에 이상이 있습니다. 캡을 제거하고 사용하기 시작하자마자 공기가 가득 차서 수축되는 것 같습니다. 35oz의 모이스처라이저가 들어 있는지 확실하지 않습니다. 다른 사람들도 같은 불만을 토로했습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "7",
            "rate": "1",
            "review-title": "Do not buy",
            "review-body": "I received the bottle and it was unsealed and barely full. I’ve used this lotion in the past and what I got is not aveeno hand cream. It feels very watered down. I do not recommend buying.",
            "review-body-translated": "병을 받았고 밀봉되지 않았고 거의 가득 찼습니다. 나는 과거에이 로션을 사용했고 내가 얻은 것은 aveeno 핸드 크림이 아닙니다. 물이 많이 빠진 느낌입니다. 구매를 권장하지 않습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "8",
            "rate": "4",
            "review-title": "Not bad but nothing special either",
            "review-body": "This lotion is moisturizing but I've seen it advertised as long-lasting, where it's supposed to last through several hand washes. Unfortunately, this is not so. You definitely need to re-apply the lotion afterwards. The price is reasonable but ultimately I'm taking a star off because it doesn't last and also for the smell, which honestly reminds me of gasoline.",
            "review-body-translated": "이 로션은 보습 효과가 있지만 몇 번 손을 씻어도 지속력이 오래 지속된다고 광고하는 것을 본 적이 있습니다. 불행히도 이것은 그렇지 않습니다. 나중에 로션을 다시 바르셔야 합니다. 가격은 합리적이지만 솔직히 휘발유가 생각나는 냄새와 지속되지 않기 때문에 궁극적으로 별을 뺍니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "9",
            "rate": "2",
            "review-title": "sticky",
            "review-body": "The first picture in the ad is not the one you get. If you scroll down you see one with blue labels which is what I got. This cream is not great. Maybe my hands aren't dry enough(I've been washing 1038292 times a day due to working in the hospital during this Covid crisis) but this lotion does not absorb well and feels sort of 'sticky' even after I wait a while for it to absorb. I'm glad it wasn't completely full in the bottle cuz I want to try something else. It also has that unscented 'scent' that was kind of strong.",
            "review-body-translated": "광고의 첫 번째 사진은 당신이 얻는 것이 아닙니다. 아래로 스크롤하면 내가 얻은 파란색 레이블이 있는 것을 볼 수 있습니다. 이 크림은 별로에요. 손이 많이 건조하지 않은 건 아닐까(이 코로나 사태에 병원 일을 하느라 하루에 1038292번을 씻었다) 그러나 이 로션은 잘 흡수되지 않고 흡수될 때까지 잠시 기다린 후에도 일종의 '끈적임'을 느낍니다. 다른 것을 시도하고 싶기 때문에 병에 완전히 채워지지 않은 것이 기쁩니다. 그것은 또한 일종의 강한 무향 '향기'를 가지고 있습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "10",
            "rate": "5",
            "review-title": "Cured my dry skin",
            "review-body": "Not sure why recently but my hands got really dry and flakey, it hurt. I got this lotion and within two days of consistent use, my hands are back to normal and feeling great.",
            "review-body-translated": "최근에 왜 그런지 모르겠지만 손이 정말 건조하고 벗겨져 아팠습니다. 나는 이 로션을 받았고 지속적으로 사용한 지 이틀 만에 손이 정상으로 돌아왔고 기분이 좋아졌습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "11",
            "rate": "2",
            "review-title": "There was no safety seal on the product!",
            "review-body": "There was no safety seal on the product, and when I went to use it (a little nervous) the bottle seems half empty!! I would really have expected there to be more product in it, and it makes me very concerned as well that there was no safety seal, so like, did someone use it then send it?",
            "review-body-translated": "제품에 안전씰도 없고 사용하러 가보니(조금 불안) 병이 반쯤 비어있는 것 같아요!! 정말 더 많은 제품이 들어있을 거라고 예상했는데, 안전씰이 없는게 너무 걱정스럽기도 하고 그래서 누가 사용하고 보낸 걸까요?",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "12",
            "rate": "1",
            "review-title": "Do not buy this",
            "review-body": "This tube came all dirty, they do not come with a seal, and it's like half the tube is air or has already been used. I bought this to go in a gift basket for someone and I would be embarrassed to give this to them in this condition.",
            "review-body-translated": "이 튜브는 더러워졌고 씰이 함께 제공되지 않으며 튜브의 절반이 공기이거나 이미 사용한 것과 같습니다. 누군가를 위한 선물 바구니에 넣으려고 샀는데 이런 상태에서 선물하기 부끄럽습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "13",
            "rate": "5",
            "review-title": "Great product- weird smell",
            "review-body": "I have eczema on my hands pretty terribly, also I’m allergic to most soaps. This product really helped but I just couldn’t get over the smell :( I can’t even describe it because it’s such an odd smell.",
            "review-body-translated": "나는 손에 습진이 아주 심하게 가지고있습니다. 또한 대부분의 비누에 알레르기가 있습니다. 이 제품은 정말 도움이 되었지만 냄새를 지울 수 없었습니다 :( 너무 기이한 냄새라 뭐라 표현할 수가 없네요..",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "14",
            "rate": "1",
            "review-title": "Clumps up",
            "review-body": "I don’t know what is wrong with this hand cream. but every time I would use it, I would be rubbing it in and it was start to like pill up into little balls and wouldn’t stay on my hands. Didn’t adsorb into hands. Don’t even bother.",
            "review-body-translated": "이 핸드크림은 뭐가 문제인지 모르겠네요. 그러나 사용하려고 할 때 마다 문지르면 알약같은 작은 공처럼 되기 시작했습으며 손에 머물지 않았습니다. 손에 흡수되지 않았습니다. 시간이 아깝습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "15",
            "rate": "4",
            "review-title": "good for dry skin",
            "review-body": "It is more moisturize than other hand cream. My hand is really dry expecially in winter, with this product, my hand can keep moisturing for longer time, but I still need it many times a day. If this product has some scent that would be better for me.",
            "review-body-translated": "다른 핸드크림에 비해 보습력이 좋아요. 특히 겨울에 손이 정말 건조한데 이 제품을 사용하면 손에 수분을 오래 유지할 수 있지만 하루에도 몇 번씩은 필요해요. 이 제품에 향이 있다면 나에게 더 좋을 것 같습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "16",
            "rate": "3",
            "review-title": "Bad shape to tube",
            "review-body": "It was what it said it was, but difficult to get out of tube once it reached halfway or so point. I felt like the usable quantity was rather low.",
            "review-body-translated": "그것은 그것이 말했던 대로이지만, 한 번 중간 정도 지점에 도달하면(사용하면) 튜브에서 빠져 나오기가 어렵습니다. 사용할 수 있는 양이 다소 적다는 느낌이 들었습니다.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "17",
            "rate": "5",
            "review-title": "Works miracles",
            "review-body": "My fingers were so cracked. It was horrifying. Nothing was working and I was at the point we're I was going to go see a doctor. I was recommended this lotion. It took about 3 weeks of applying 3x a day and it completely disappeared. I use it now for my feet and face. It's feels amazing and the scent is so good.",
            "review-body-translated": "내 손가락들은 너무 갈라졌었습니다. 그것은 끔찍했었습니다. 어떤ㅓ도 효과가 없었고 의사에게 진찰을 받으러 가야 하는 시점에 있었습니다. 이 로션을 추천받았습니다. 하루 3번 바르는데 3주정도 걸리더니 완전히 사라졌습니다. 나는 지금 내 발과 얼굴에 그것을 사용합니다. 기분도 좋고 향도 너무 좋아요.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "18",
            "rate": "3",
            "review-title": "Seller did awesome. Product OK.",
            "review-body": "I wash my hands thouroughly and a LOT. I love Aveeno products but this just wasnt enough. It's a good product but for dry hands that get a lot of washing, this just didn't cut it.",
            "review-body-translated": "나는 손을 철저히 씻습니다. 나는 Aveeno 제품을 좋아하지만 이것만은 충분히 좋지 않습니다. 좋은 제품이지만 손을 많이 씻는 건성 손에게는 잘 안 잡히더라고요.",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "19",
            "rate": "2/5",
            "review-title": "Package And Description Changed, Product The Same",
            "review-body": "I failed to double check the ingredients so the fault of the purchase was mine but still... This product is a disappointment. The product is NOT a cream. You could pump it from a lotion bottle easily. It isn't greasy and it is an unscented product that really has no scent at all so at least 2 stars in its favor. For now I'm still using Cetaphil cream.I really miss Aveeno's older product lines ;<(",
            "review-body-translated": "원재료를 재차 확인하지 못해 구매의 잘못이 제 잘못이지만 그래도... 이 제품은 실망입니다. 제품은 크림이 아닙니다. 로션 병에서 쉽게 펌핑할 수 있습니다. 끈적임도 없고 정말 향이 전혀 없는 무향 제품이라 별점 2개 이상입니다. 아직까지는 세타필 크림을 쓰고 있습니다. 아비노의 예전 제품 라인이 정말 그립습니다. ;<(",
            "helpfulness-rating": null,
        },
        {
            "product": "hand cream",
            "review-number" : "20",
            "rate": "4",
            "review-title": "Not bad but nothing special either",
            "review-body": "This lotion is moisturizing but I've seen it advertised as long-lasting, where it's supposed to last through several hand washes. Unfortunately, this is not so. You definitely need to re-apply the lotion afterwards. The price is reasonable but ultimately I'm taking a star off because it doesn't last and also for the smell, which honestly reminds me of gasoline.",
            "review-body-translated": "이 로션은 보습 효과가 있지만 몇 번 손을 씻어도 지속력이 오래 지속된다고 광고하는 것을 본 적이 있습니다. 불행히도 이것은 그렇지 않습니다. 나중에 로션을 다시 바르셔야 합니다. 가격은 합리적이지만 솔직히 휘발유가 생각나는 냄새와 지속되지 않기 때문에 궁극적으로 별을 뺍니다.",
            "helpfulness-rating": null,
        },

    ]
}